import people from './icons/people.svg'
import sqaure from './icons/square.svg'
import euro from './icons/euro.svg'
import leftArrow from './icons/leftArrow.svg'
import rightArrow from './icons/rightArrow.svg'
import close from './icons/close.svg'
import burger from './icons/burger.svg'
import rentspace_cover from './images/rentspace_cover.jpg'
import git from './icons/git.svg'
import linkedin from './icons/linkedin.svg'
export { people, sqaure, euro, leftArrow, rightArrow, close, burger, rentspace_cover, git, linkedin }  
